version: '3.1'

services:
  mysql_db:
    image: mysql:8.4
    container_name: 'java-city-market-DB'
#    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: myDB
      MYSQL_USER: user
      MYSQL_PASSWORD: 1111

