spring.application.name:  manager-app

spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/manager
    username: manager
    password: manager

city-market:
  services:
    catalogue:
      uri: http://localhost:8081
      user: "catalogue_service_user"
      password: password