
spring:

  datasource:
    url: jdbc:postgresql://localhost:5432/postgre_db
    username: user
    password: 1234

  flyway:
    schemas:
      - public
      - catalogue
  jpa:
    show-sql: true

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8082/realms/citymarket

server:
  port: 8081

logging:
  level:
    sql: info

